name: Build 

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build-maven:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Java ${{ matrix.Java }} (${{ matrix.os }})
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-m2-repository-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2-repository
    - name: Build with Maven
      env:
        MAVEN_OPTS: -Dhttps.protocols=TLSv1.2 -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.requestSentEnabled=true -Dmaven.wagon.http.retryHandler.count=10
      run: mvn --batch-mode --errors --update-snapshots verify --file pom.xml 
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.java }}
        retention-days: 5
        path:  |
          jee-agents-distribution/jee-agents-distribution-appserver-v10/target/*.zip
          jee-agents-distribution/jee-agents-distribution-jboss-v42/target/*.zip
          jee-agents-distribution/jee-agents-distribution-jboss-v7/target/*.zip
          jee-agents-distribution/jee-agents-distribution-jetty-v61/target/*.zip
          jee-agents-distribution/jee-agents-distribution-jetty-v7/target/*.zip
          jee-agents-distribution/jee-agents-distribution-jsr196/target/*.zip
          jee-agents-distribution/jee-agents-distribution-tomcat-v6/target/*.zip