name: Package/Deploy 

on:
  workflow_dispatch:
  workflow_run:
    branches: [ master ]
    workflows: ["Build","Release"]
    types: [completed]
jobs:
  deploy-maven:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set up Java for publishing to Maven Central Repository OSS
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-m2-repository-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2-repository
      - name: Install gpg secret key
        env:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        if: ${{ env.GPG_PRIVATE_KEY!=''}}
        run: |
           cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
           gpg --list-secret-keys --keyid-format LONG
      - name: Build package local
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_OPTS: -Dhttps.protocols=TLSv1.2 -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.requestSentEnabled=true -Dmaven.wagon.http.retryHandler.count=10
        if: ${{ !(github.event.workflow_run.event=='push' && env.MAVEN_USERNAME!='' && env.MAVEN_PASSWORD!='')}}
        run: mvn --batch-mode --errors --update-snapshots -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} package --file pom.xml
      - name: Publish to the Maven Central Repository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_OPTS: -Dhttps.protocols=TLSv1.2 -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.requestSentEnabled=true -Dmaven.wagon.http.retryHandler.count=10
        if: ${{ github.event.workflow_run.event=='push' && env.MAVEN_USERNAME!='' && env.MAVEN_PASSWORD!=''}}
        run: mvn --batch-mode --errors --update-snapshots -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} deploy --file pom.xml
      - name: Upload artifacts OpenAM Distribution Kit, containing all distributable artifacts
        uses: actions/upload-artifact@v3
        with:
         name: OpenAM Java Policy Agent (Appserver v10 ZIP)
         path: jee-agents-distribution/jee-agents-distribution-appserver-v10/target/*.zip
      - name: Upload artifacts OpenAM Distribution Kit, containing all distributable artifacts
        uses: actions/upload-artifact@v3
        with:
         name: OpenAM Java Policy Agent (JBoss v42 ZIP)
         path: jee-agents-distribution/jee-agents-distribution-jboss-v42/target/*.zip
      - name: Upload artifacts OpenAM Distribution Kit, containing all distributable artifacts
        uses: actions/upload-artifact@v3
        with:
         name: OpenAM Java Policy Agent (JBoss v7 ZIP)
         path: jee-agents-distribution/jee-agents-distribution-jboss-v7/target/*.zip
      - name: Upload artifacts OpenAM Distribution Kit, containing all distributable artifacts
        uses: actions/upload-artifact@v3
        with:
         name: OpenAM Java Policy Agent (Jetty v61 ZIP)
         path: jee-agents-distribution/jee-agents-distribution-jetty-v61/target/*.zip
      - name: Upload artifacts OpenAM Distribution Kit, containing all distributable artifacts
        uses: actions/upload-artifact@v3
        with:
         name: OpenAM Java Policy Agent (Jetty v7-v8 ZIP)
         path: jee-agents-distribution/jee-agents-distribution-jetty-v7/target/*.zip
      - name: Upload artifacts OpenAM Distribution Kit, containing all distributable artifacts
        uses: actions/upload-artifact@v3
        with:
         name: OpenAM Java Policy Agent (JSR196 ZIP)
         path: jee-agents-distribution/jee-agents-distribution-jsr196/target/*.zip
      - name: Upload artifacts OpenAM Distribution Kit, containing all distributable artifacts
        uses: actions/upload-artifact@v3
        with:
         name: OpenAM Java Policy Agent (Tomcat v6 v7 v8 v9 ZIP) 
         path: jee-agents-distribution/jee-agents-distribution-tomcat-v6/target/*.zip
  